More timestamps as dependent
Georacer/ardupilog pull request #48
Opened 2017-04-17 15:38 UTC by hunt0r

This is a first attempt at implementing TimeS and UTC time as dependent properties. As we begin to use these, we will likely evolve how they're implemented internally.

I ran into a number of issues for discussion, so I've put comments in the code and I'll summarize them here:
1) We had envisioned TimeUTC as the dependent property, but I wasn't sure how we would implement that? I used instead DatenumUTC, using MATLAB's datenum, which is the number of days since Jan 00, year 0000.
2) For this first-attempt, I assume that the first GPS log message (containing GWk and GMS info) was received at its TimeUS timestamp. Note this is NOT true, as TimeUS measures its time-of-logging, not it's receipt time. (I expect less than a second of error from this.) We can get more accurate by using the GPA messages, or by requesting Ardupilot change some logging, but I went ahead with this for now.
3) This PR merges easily with all the other outstanding PRs #46 and #47 . In the future, if we refactor the code further, we might want to modify how/when the bootTimeUTC is passed to all the LogMsgGroups.

2017-04-17 22:25 UTC, hunt0r commented
So I don't forget them, here are the "sneaky bugs" I found:
1) The merge still has createLogMsgGroups() where I updated the addprop() call to catch the handles, but in the "flattened" main code, addprop is originally called without catching the handle.
2) At the end of LogMsgGroup.getSlice(), don't forget to set the bootDatenumUTC after setting the LineNo

2017-04-26 12:43 UTC, Georacer commented
What is the status of this, regarding yesterday's talk on avoiding "flattening" of functions?

2017-04-26 12:53 UTC, Georacer requested changes
I like it. Can you make the requested change and I'll merge it.

2017-04-26 12:53 UTC, Georacer commented on Ardupilog.m
> +                for prop = properties(obj)'
I think a better check should be
isa(obj.(prop{1}),'LogMsgGroup')

It is more clear that we want to only set the boot time for logmsggroup objects

2017-04-26 12:53 UTC, Georacer commented on Ardupilog.m
> +                     'Jul 01 2015'], 'mmm dd yyyy');
Can you cite this from somewhere? Wheren't sometimes leap seconds removed, instead of added?

2017-04-26 12:53 UTC, Georacer commented on LogMsgGroup.m
> +        function timeS = get.TimeS(obj)
Nice, melikes

2017-04-26 16:48 UTC, hunt0r commented on Ardupilog.m
> +                     'Jul 01 2015'], 'mmm dd yyyy');
Added above, new line 341 and 342

2017-04-26 16:48 UTC, hunt0r commented on Ardupilog.m
> +                for prop = properties(obj)'
Changed.

2017-04-26 16:50 UTC, Georacer approved these changes

2017-04-26 16:53 UTC, Georacer commented
Looks fine now. It conflicts with getSlice, but I'll try to resolve it online.

2017-04-26 16:55 UTC, merged

2017-04-26 16:58 UTC, Georacer commented
It was a botch job after all, we should have rebased the branch onto master as usual. Can you make sure getSlice and more-timestamps work as intended?
Thanks