Ardupilot system identification automation initial support
Georacer/ardupilog pull request #84
Opened 2021-05-19 17:19 UTC by amilcarlucas

First run sid_pre to read in the relevant parts of your .bin log files.
Run it iteratively doing changes in the sid_pre_config.m file as necessary.

Once you are happy with it, run sid_plot.
Run it iteratively doing changes in the sid_plot_config.m file as necessary.

2021-05-19 18:47 UTC, Georacer commented
I see that this depends on the previous PRs you made today, some of which need fixing.

We'll revisit this after we deal with those and you rebase, ok?

2021-05-19 19:00 UTC, amilcarlucas commented
yeap, thanks.

2021-05-19 19:50 UTC, Georacer commented
I'm having a hard time understanding what this PR is about.
Looks like it plots the System Identification results, without doing any further manipulation.
But I can't run it myself without the logs mentioned in sid_pre_config.m. Could you provide them?

Still, in a more general frame, Ardupilog was strictly meant to be a log converter, not focused on any specific application.
If I understand your code correctly, it indeed does only visualization, but over more than one logs.

I'll have to give some more thought on whether it fits the Ardupilog purpose and how I could re-structure the codebase to include tools spanning more than one log.
But, by all means, please provide the logs, it will make this process so much easier.

Thanks!

2021-05-20 10:51 UTC, amilcarlucas commented
The example files are available here https://we.tl/t-KXhvCNx6LL

yes, I'm also not sure if the SID tool belongs in the Ardupilog repo, but the SID tool is a nice example on how to use Ardupilog.

2021-05-20 23:30 UTC, Georacer commented
I was not aware of the system identification Mode in Arducopter. Cool stuff!

Yes, for sure this doesn't belong to the main Ardupilog repo, but I'd be happy to present this as a use-case.
I could get a proper documentation page going (readthedocs or similar) and post it there.

I will probably need your help to make it an educational tutorial.

Are you ok with this approach?

2021-05-20 23:42 UTC, amilcarlucas commented
Yes, I plan to continue to work on the tool, automating data import into the systemIdentification toolbox and eventually automate the entire system identification workflow.

I would love to collaborate.

2021-05-26 20:25 UTC, Georacer commented
Hi Lucas,
Since there's a separate "stable" branch now, I feel happy to merge this when you want, even if it's incomplete.

Just rebase on the current master, put the files in the `gallery/sid` folder and let me know.

2025-09-26 13:32 UTC, amilcarlucas commented
Would be nice to get this in !

2025-09-26 14:03 UTC, Georacer requested changes
Hi Amilcar!

As I mentioned above, I'd prefer if you placed your files into the `gallery/sid` subfolder.
`ardupilog` is meant to be primarily a library and parsing tool, so SysID functionality doesn't have a place on the front-page.

Also, could you squash your commits into one? Or at least to as few as logically reasonable.

Thanks!

2025-09-26 14:38 UTC, amilcarlucas commented
done

2025-09-26 20:57 UTC, Georacer approved these changes

2025-09-26 20:57 UTC, Georacer commented
Thanks! It's not crucial, but you don't actually give instructions on the usage of the `sid_ana.m` file. If you feel like it, make an update.

2025-09-26 20:58 UTC, merged